# Generated by Django 4.1.3 on 2024-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprices',
            name='request_time',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dailyprices',
            name='session_date',
            field=models.DateField(unique=True),
        ),
    ]
