# Generated by Django 4.1.3 on 2024-01-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binance_data', '0003_platformexchange_remove_dailyprices_asset_symbol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetsymbol',
            options={'verbose_name': 'Asset Symbol', 'verbose_name_plural': 'Asset Symbols'},
        ),
        migrations.AlterModelOptions(
            name='platformexchange',
            options={'verbose_name': 'Platform Exchange', 'verbose_name_plural': 'Platform Exchanges'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'verbose_name': 'Sector', 'verbose_name_plural': 'Sectors'},
        ),
        migrations.AlterModelTable(
            name='assetsymbol',
            table='asset_symbol',
        ),
        migrations.AlterModelTable(
            name='platformexchange',
            table='platform_exchange',
        ),
        migrations.AlterModelTable(
            name='sector',
            table='sector',
        ),
    ]
