# Generated by Django 4.1.3 on 2024-01-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binance_data', '0004_alter_assetsymbol_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprices',
            name='type_of_asset',
            field=models.CharField(choices=[('B', 'base'), ('F', 'futures contract'), ('O', 'options')], default='B', max_length=1),
        ),
    ]
