# Generated by Django 4.1.3 on 2024-01-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('asset_full_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Asset Symbol',
                'verbose_name_plural': 'Asset Symbols',
                'db_table': 'asset_symbol',
            },
        ),
        migrations.CreateModel(
            name='PlatformExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='not_set', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Platform Exchange',
                'verbose_name_plural': 'Platform Exchanges',
                'db_table': 'platform_exchange',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='not_set', max_length=50, unique=True)),
                ('platform_exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_data.platformexchange')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='DailyPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(unique=True)),
                ('request_time', models.DateTimeField(blank=True, null=True, unique=True)),
                ('price_day_open', models.FloatField(blank=True, null=True)),
                ('price_day_high', models.FloatField(blank=True, null=True)),
                ('price_day_low', models.FloatField(blank=True, null=True)),
                ('price_day_close', models.FloatField(blank=True, null=True)),
                ('day_volume', models.FloatField(blank=True, null=True)),
                ('day_true_range', models.FloatField(blank=True, null=True)),
                ('day_average_true_range', models.FloatField(blank=True, null=True)),
                ('type_of_asset', models.CharField(choices=[('B', 'base'), ('F', 'futures contract'), ('O', 'options')], default='B', max_length=1)),
                ('symbol', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='get_data.assetsymbol')),
            ],
            options={
                'verbose_name': 'Symbol Daily Prices (TR, ATR)',
                'verbose_name_plural': 'Symbol Daily Prices (TR, ATR)',
                'db_table': 'daily_prices',
                'ordering': ['session_date'],
            },
        ),
        migrations.AddField(
            model_name='assetsymbol',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='get_data.sector'),
        ),
    ]
