# Generated by Django 4.1.3 on 2024-01-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyprices',
            name='type_of_asset',
        ),
        migrations.AddField(
            model_name='assetsymbol',
            name='type_of_asset',
            field=models.CharField(choices=[('B', 'base'), ('F', 'futures contract'), ('O', 'options')], default='B', max_length=1),
        ),
    ]
