# Generated by Django 4.1.3 on 2024-01-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0002_remove_dailyprices_type_of_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetsymbol',
            name='type_of_asset',
            field=models.CharField(choices=[('S', 'spot'), ('F', 'futures contract'), ('O', 'options')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='dailyprices',
            name='day_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
