# Generated by Django 4.1.3 on 2024-01-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0003_alter_assetsymbol_type_of_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprices',
            name='session_date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprices',
            unique_together={('symbol', 'session_date')},
        ),
    ]
