# Generated by Django 4.1.3 on 2024-01-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0004_alter_dailyprices_session_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyprices',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='dailyprices',
            name='request_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprices',
            unique_together={('symbol', 'request_time')},
        ),
    ]
