# Generated by Django 4.1.3 on 2024-01-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0005_alter_dailyprices_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprices',
            options={'ordering': ['-session_date'], 'verbose_name': 'Symbol Daily Prices (TR, ATR)', 'verbose_name_plural': 'Symbol Daily Prices (TR, ATR)'},
        ),
        migrations.AlterField(
            model_name='dailyprices',
            name='day_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
