# Generated by Django 4.1.3 on 2024-02-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0006_alter_dailyprices_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyprices',
            unique_together={('symbol', 'session_date')},
        ),
    ]
