# Generated by Django 4.1.3 on 2024-02-22 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0007_alter_dailyprices_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATRs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('day_average_true_range', models.FloatField(blank=True, null=True)),
                ('symbol', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='get_data.assetsymbol')),
            ],
        ),
    ]
