# Generated by Django 4.1.3 on 2024-02-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0008_atrs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ATRs',
        ),
    ]
