# Generated by Django 4.1.3 on 2024-02-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0009_delete_atrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('session_date', models.DateField()),
                ('day_average_true_range', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atr',
                'unique_together': {('symbol', 'session_date')},
            },
        ),
    ]
