# Generated by Django 4.1.3 on 2024-02-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0010_atr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ATR',
        ),
    ]
