# Generated by Django 4.1.3 on 2024-02-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0010_atr'),
    ]

    operations = [
        migrations.AddField(
            model_name='atr',
            name='day_true_range',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atr',
            name='day_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atr',
            name='price_day_close',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atr',
            name='price_day_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atr',
            name='price_day_low',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atr',
            name='price_day_open',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
