# Generated by Django 4.1.3 on 2024-02-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0011_atr_day_true_range_atr_day_volume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atr',
            old_name='day_average_true_range',
            new_name='Close',
        ),
        migrations.RenameField(
            model_name='atr',
            old_name='day_true_range',
            new_name='High',
        ),
        migrations.RenameField(
            model_name='atr',
            old_name='day_volume',
            new_name='Low',
        ),
        migrations.RenameField(
            model_name='atr',
            old_name='price_day_close',
            new_name='Open',
        ),
        migrations.RenameField(
            model_name='atr',
            old_name='price_day_high',
            new_name='Volume',
        ),
        migrations.RenameField(
            model_name='atr',
            old_name='price_day_low',
            new_name='atr',
        ),
        migrations.RenameField(
            model_name='atr',
            old_name='session_date',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='atr',
            old_name='price_day_open',
            new_name='tr',
        ),
        migrations.AlterUniqueTogether(
            name='atr',
            unique_together={('symbol', 'session')},
        ),
    ]
