# Generated by Django 4.1.3 on 2024-02-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0011_delete_atr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('session', models.DateField()),
                ('Open', models.FloatField(blank=True, null=True)),
                ('High', models.FloatField(blank=True, null=True)),
                ('Low', models.FloatField(blank=True, null=True)),
                ('Close', models.FloatField(blank=True, null=True)),
                ('Volume', models.FloatField(blank=True, null=True)),
                ('tr', models.FloatField(blank=True, null=True)),
                ('atr', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'atr',
                'unique_together': {('symbol', 'session')},
            },
        ),
    ]
