# Generated by Django 4.1.3 on 2024-03-04 15:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0012_atr'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprices',
            name='atr_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None, verbose_name='ATRs Levels'),
        ),
    ]
