# Generated by Django 4.1.3 on 2024-03-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0014_two_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='two_hours',
            old_name='request_time',
            new_name='end_of_candle',
        ),
        migrations.RenameField(
            model_name='two_hours',
            old_name='time_of_candle',
            new_name='start_of_candle',
        ),
        migrations.AlterUniqueTogether(
            name='two_hours',
            unique_together={('symbol', 'start_of_candle')},
        ),
    ]
