# Generated by Django 4.1.3 on 2024-03-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0016_atr_ma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atr',
            name='ma',
        ),
        migrations.AddField(
            model_name='atr',
            name='ma10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atr',
            name='ma20',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atr',
            name='ma5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
