# Generated by Django 4.1.3 on 2024-03-11 15:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0017_remove_atr_ma_atr_ma10_atr_ma20_atr_ma5'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprices',
            name='prev_two_ses_high_low',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None, verbose_name='H/L P2Ses'),
        ),
    ]
