# Generated by Django 4.1.3 on 2024-03-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0018_dailyprices_prev_two_ses_high_low'),
    ]

    operations = [
        migrations.AlterField(
            model_name='two_hours',
            name='end_of_candle',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='two_hours',
            name='start_of_candle',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
