# Generated by Django 4.1.3 on 2024-03-19 18:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0020_two_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='MP_Two_Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=50)),
                ('session', models.DateField()),
                ('top_tail', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None, verbose_name='top tail')),
                ('body', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None, verbose_name='body')),
                ('body_size_ticks', models.FloatField(blank=True, null=True)),
                ('body_size_percent', models.FloatField(blank=True, null=True)),
                ('bottom_tail', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None, verbose_name='ATRs Levels')),
                ('periods_mp', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None, verbose_name='visual market profile')),
            ],
        ),
        migrations.AlterModelOptions(
            name='dailyprices',
            options={'ordering': ['-session_date'], 'verbose_name': 'Daily (TR, ATR, ATR levs, 2SesHL)', 'verbose_name_plural': 'Daily (TR, ATR, ATR levs, 2SesHL)'},
        ),
        migrations.AlterField(
            model_name='dailyprices',
            name='prev_two_ses_high_low',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None, verbose_name='H/L 2 Prev Ses'),
        ),
    ]
