# Generated by Django 4.1.3 on 2024-03-19 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0021_mp_two_hours_alter_dailyprices_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MP_Two_Hours',
        ),
    ]
