# Generated by Django 4.1.3 on 2024-03-19 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0023_mp_two_hours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MP_Two_Hours',
        ),
    ]
