# Generated by Django 4.1.3 on 2024-03-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0025_mp_two_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mp_two_hours',
            options={'ordering': ['symbol', '-session'], 'verbose_name': 'MP Two Hours', 'verbose_name_plural': 'MP Two Hours'},
        ),
        migrations.AlterModelOptions(
            name='two_hours',
            options={'ordering': ['symbol', '-session_date'], 'verbose_name': 'Two Hours', 'verbose_name_plural': 'Two Hours'},
        ),
        migrations.AddField(
            model_name='mp_two_hours',
            name='bottom_tail_percent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mp_two_hours',
            name='top_tail_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
