# Generated by Django 4.1.3 on 2024-03-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0026_alter_mp_two_hours_options_alter_two_hours_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atr',
            options={'ordering': ['symbol', '-session']},
        ),
        migrations.AlterModelOptions(
            name='dailyprices',
            options={'ordering': ['symbol', '-session_date'], 'verbose_name': 'Daily (TR, ATR, ATR levs, 2SesHL)', 'verbose_name_plural': 'Daily (TR, ATR, ATR levs, 2SesHL)'},
        ),
        migrations.AddField(
            model_name='mp_two_hours',
            name='periods_visualization',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
