# Generated by Django 4.1.3 on 2024-03-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0027_alter_atr_options_alter_dailyprices_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20)),
                ('session', models.DateField()),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('futures_pos', models.FloatField(blank=True, null=True)),
                ('max_prc_stop', models.FloatField(blank=True, null=True)),
                ('amount_of_position', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'RT Celery',
                'verbose_name_plural': 'RT Celery',
                'db_table': 'realtime_celery',
                'ordering': ['symbol', '-session'],
            },
        ),
    ]
