# Generated by Django 4.1.3 on 2024-03-23 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0028_realtimedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimedata',
            name='request_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
