# Generated by Django 4.1.3 on 2024-03-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0029_realtimedata_request_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimedata',
            name='atr_prc_passed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
