# Generated by Django 4.1.3 on 2024-03-26 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0030_realtimedata_atr_prc_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimedata',
            name='today_two_ses',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
