# Generated by Django 4.1.3 on 2024-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0031_realtimedata_today_two_ses'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimedata',
            name='ysd_body_level',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
