# Generated by Django 4.1.3 on 2024-03-28 14:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_data', '0033_realtimedata_ysd_body_border_realtimedata_ysd_tail'),
    ]

    operations = [
        migrations.AddField(
            model_name='realtimedata',
            name='atr_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
